[package]
name = "integracion_arca"
version = "0.1.0"
edition = "2024"

[dependencies]
base64           = { version = "0.22.1" , default-features = false, optional= true }
chrono           = { version = "0.4.45" , default-features = false, optional= true , features = ["serde", "now"] }
dashmap          = { version = "6.2.1"  , default-features = false, optional= true }
encoding_rs      = { version = "0.8.35", optional = false} 
futures = "0.3.34"
openssl          = { version = "0.10.81", default-features = false, optional= true , features = ["vendored"] }
qrcode-generator = { version = "5.0.0"  , default-features = false, optional= true , features = ["image"] }
quick-xml        = { version = "0.42.0", features = ["serialize", "tokio"] }
reqwest          = { version = "0.13.4", default-features = false, optional = true, features = ["rustls"] }
serde            = { version = "1.0.229", default-features = false, optional= false, features = ["derive"] }
serde_json       = { version = "1.0.151", default-features = false, optional= false, features = ["std"] }
tracing          = { version = "0.1.44", default-features = false, features = ["attributes"] }
utoipa           = { version = "5.5.0", optional = true, features = ["chrono"] }

[dev-dependencies]
dotenvy = "0.15.7"
tokio   = { version = "1.53.1" , default-features = false, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }




[features]
wsaa                    = ["dep:openssl", "dep:chrono", "dep:dashmap"]
dummy_type              = []
qr_make                 = ["dep:qrcode-generator","dep:base64"]
utoipa                  = ["dep:utoipa"]

wsfev1                  = []
wsfev1_dummy            = ["wsfev1","dummy_type","dep:reqwest"]
wsfev1_fe_cae_solicitar = ["wsfev1","wsaa", "dep:reqwest"]

wsfexv1                 = []
wsfexv1_dummy           = ["wsfexv1","dummy_type","dep:reqwest"]

wsmtxca                 = []
wsmtxca_dummy           = ["wsmtxca","dummy_type","dep:reqwest"]

wscpe                   = []
wscpe_dummy             = ["wscpe","dummy_type","dep:reqwest"]

wslpg                   = []
wslpg_dummy             = ["wslpg","dummy_type","dep:reqwest"]

wsbfev1                 = []
wsbfev1_dummy           = ["wsbfev1","dummy_type","dep:reqwest"]

ws-sr-padron-a13            = []
ws-sr-padron-a13_dummy      = ["ws-sr-padron-a13","dep:reqwest","dummy_type"]
ws-sr-padron-a13_get_by_cuit= ["ws-sr-padron-a13","dep:reqwest","wsaa"]
ws-sr-padron-a13_get_by_dni = ["ws-sr-padron-a13","dep:reqwest","ws-sr-padron-a13_get_by_cuit"]

